Lesson-15
DmitryKilin/qna pull request #15
Opened 2019-12-21 20:42 UTC by DmitryKilin

2019-12-24 09:38 UTC, vkurennov requested changes

2019-12-24 09:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def perfom_subscription
Это, конечно, же неправильно. Во-первых, это часть бизнес-логики и она должна быть в моделях, во-вторых, у тебя, например, есть апи и создав ответ через него, подписка создана не будет. Нужно дублировать  код. Но ведь в модели есть коллбеки, привязанные к жизненному циклу (и они как раз являются частю бизнес-логики), гораздо логичнее разместить это там. Так будет одна точка изменений.

2019-12-24 09:38 UTC, vkurennov commented on app/views/subscriptions/_subscription.html.slim
> +              subscription_path(current_user.subscriptions.where(question: resource).first),
делать такой запрос в видах - не очень идея. лучше метод у юзера сделать, возвращающий подписку

2019-12-24 09:38 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        #Нужно ли проверять вызов SubscriptionJob в контроллере  и как передать в with(Answer)
его нужно перенести в модель и проверять там

2019-12-24 19:38 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def perfom_subscription
fixed

2019-12-24 20:03 UTC, DmitryKilin commented on app/views/subscriptions/_subscription.html.slim
> +              subscription_path(current_user.subscriptions.where(question: resource).first),
fixed

2019-12-24 20:03 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        #Нужно ли проверять вызов SubscriptionJob в контроллере  и как передать в with(Answer)
fixed

2019-12-25 09:12 UTC, vkurennov approved these changes

2019-12-25 14:59 UTC, merged