Lesson 5
DmitryKilin/qna pull request #3
Opened 2019-06-23 19:21 UTC by DmitryKilin

2019-06-24 08:01 UTC, vkurennov requested changes

2019-06-24 08:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
Где удаление? В задании есть третий блок с историями про удаление вопросов и ответов

2019-06-24 08:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
не могу к предыдущему коду оставить комментарий, поэтому здесь напишу: new для ответов не нужен, т.к. форма должна ренедриться на странице вопроса

2019-06-24 08:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def create
раз форма на странице вопроса, то и при невалидных данных нужно рендерить questions/show

2019-06-24 08:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit( :body, :question_id )
question_id не приходит в данных формы, он приходит в url, т.е. просто в `params`, а не в `params[:answer]`

2019-06-24 08:01 UTC, vkurennov commented on app/controllers/questions_controller.rb
у нас удалять вопросы может только автор, значит, на уровне контроллера должна быть проверка на это, даже если в видах она уже есть, т.к. легко сделать запрос напрямую, в обход вида. Любые правила авторизации (т.е. может юзер выполнить то или иное действие или нет) обязательно проверяются на уровне контроллера.

2019-06-24 08:01 UTC, vkurennov commented on app/views/answers/new.html.slim
> += form_with model: @answer do |f|
этот вид не нужен, т.к. у тебя форма на странице вопроса

2019-06-24 08:01 UTC, vkurennov commented on app/views/questions/index.html.slim
> +p= link_to 'Log out', destroy_user_session_path, method: :delete
эти ссылки должны быть в лейауте, чтобы были на любой странице

2019-06-24 08:01 UTC, vkurennov commented on app/views/questions/index.html.slim
> +h1= 'Questions list'
тут логично вывести и сам список вопросов

2019-06-24 08:01 UTC, vkurennov commented on app/views/questions/show.html.slim
> += @question.id
это зачем? id - это внутренняя информация, юзеру она не нужна

2019-06-24 08:01 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_with model: [ @question, @answer ], local: true do |f|
здесь надо добавить вывод ошибок валидации для ответа и из контроллера рендерить эту страницу

2019-06-24 08:01 UTC, vkurennov commented on config/routes.rb
>      resources :answers, only: %i[new create show]
new и show для ответа не нужны. а вот destroy нужен

2019-06-24 08:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'GET #new' do
new не нужен, как и тесты для него

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +  # Не могу понять почему не работает!:
а что именно не работает?

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +  scenario do
к сценариям надо писать описание

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +    visit question_path(question)
нет, так ты просто страницу перезагружаешь получается. У тебя же должно быть как: ввел ответ, нажал сохранить - ответ есть на странице. Без повторного захода на страницу

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +feature 'User can create answer', %q{
не надо на каждый сценарий новую фичу писать. у тебя есть одна фича - создание ответа, в ней разные сценарии: успешное создание, невалидный ответ, незалогиненный юзер и т.д. все в одной фиче

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +  # Не могу понять почему не работает!:
кажется, я догодался. на самом деле все работает, просто ты используешь здесь локальную переменную и она не видна в тестах. тут либо инстанс-переменные надо использовать, либо вынести в given создание вопроса

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +  given(:user) { User.create!(email: 'user@test.com', password: '12345678') }
используй фабрику для создания юзеров

2019-06-24 08:01 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +    question = create(:question, :with_answers)
перенеси в given создание вопроса, тогда `visit` можно будет перенести в `background`

2019-06-24 08:01 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +    given(:user) { User.create!(email: 'user@test.com', password: '12345678') }
используй фабрику

2019-06-24 08:01 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +feature 'User can view the questions list' do
каждая фича - в отдельном файле. здесь у тебя создание, список - в другом файле

2019-06-24 08:01 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +    expect(page).to have_content 'Questions list'
это только проверяет наличие заголовка на странице, но не проверяет наличие списка вопросов. в итоге, фича у тебя реализована не верно и твои тесты тебе об этом не сказали, значит, набор тестов не полный. Нужно создать несколько разных вопросов (используй sequence в фабриках для этого) и проверить, что они есть на странице

2019-06-24 08:02 UTC, aishek requested changes

2019-06-24 08:02 UTC, aishek commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
Не хватает удаления ответа.

И в ветке создания ответа с ошибкой надо рендерить страницу вопроса.

2019-06-24 08:02 UTC, aishek commented on app/controllers/questions_controller.rb
>    end
В этом контроллере не хватает кода, который будет разрешать удаление только своего вопроса.

2019-06-24 08:02 UTC, aishek commented on app/views/questions/show.html.slim
> += @question.id
Похоже на отладочный код.

2019-06-24 08:02 UTC, aishek commented on config/routes.rb
> +  resources :questions, shallow: true do
Не к вопросам, а к ответам. Цель в том, чтобы передавать в роут-хелперы не вопрос и ответ (как происходит в случае вложенных роутов), а один — только вопрос https://guides.rubyonrails.org/routing.html#shallow-nesting

2019-06-24 08:02 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
И в реквесте видны не все изменения. Судя по-всему, работа была начата в ветке `master`, а затем продолжена в отдельной ветке. Не надо так, смотреть вообще не удобно.

В создании не хватает проверки на авторство только что созданного ответа.

2019-06-24 08:02 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
В создании нужно проверить принадлежность пользователю.

В удалении нужно проверить случай удаления чужого вопроса.

2019-06-24 08:02 UTC, aishek commented on spec/features/answer/create_spec.rb
> +  #   question = create(:question, :with_answers)
Это лучше делать через `given`

2019-06-24 08:02 UTC, aishek commented on spec/features/answer/create_spec.rb
> +  # Не могу понять почему не работает!:
Какой текст ошибки?

2019-06-24 08:02 UTC, aishek commented on spec/features/answer/create_spec.rb
> +feature 'User can write an answer for question', %q{
Нужен кейс с неправильно заполненными полями ответа.

2019-06-24 08:02 UTC, aishek commented on spec/features/question/create_spec.rb
> +    expect(page).to have_content 'Questions list'
Тут нужно проверить что все существующие в системе вопросы выводятся.

2019-06-24 08:02 UTC, aishek commented on spec/features/sign_in_spec.rb
> +  # Проглядел все глаза, не пойму почему при использовании конструкции `given` в браузере выводится,
Надо смотреть в `log/test.log` во время выполнения теста. Ещё может помочь отладочная печать в контроллере.

2019-06-24 08:02 UTC, aishek commented on spec/features/sign_up_spec.rb
> +  scenario "Visitor fills correct the register form, clicks the 'Sign up' button and redirects to the confirmation page" do
Нужно проверить кейс с неправильно заполненной формой.

2019-06-24 08:02 UTC, aishek commented on spec/features/question/create_spec.rb
>    As an authenticated user
Ещё не вижу проверок сценариев с удалением.

2019-06-24 14:58 UTC, DmitryKilin commented on spec/features/answer/create_spec.rb
> +feature 'User can write an answer for question', %q{
В ответе есть лишь поле "body". Не могу представить, как его можно заполнить не так? Только если оставить его пустым?

2019-06-24 15:01 UTC, DmitryKilin commented on spec/features/sign_in_spec.rb
> +  # Проглядел все глаза, не пойму почему при использовании конструкции `given` в браузере выводится,
Спасибо!

2019-06-24 15:04 UTC, DmitryKilin commented on spec/features/sign_up_spec.rb
> +  scenario "Visitor fills correct the register form, clicks the 'Sign up' button and redirects to the confirmation page" do
Нужно ли проверять реакцию `Devise` на не правильно заполненную форму регистрации пользователя?

2019-06-24 18:24 UTC, aishek commented on spec/features/sign_up_spec.rb
> +  scenario "Visitor fills correct the register form, clicks the 'Sign up' button and redirects to the confirmation page" do
Да.

2019-06-29 19:13 UTC, aishek requested changes

2019-06-29 19:13 UTC, aishek commented on app/controllers/answers_controller.rb
> +  def create
Не надо оставлять отладочную печать.

Проверки входных данных по соглашениям Rails выносятся в модели в виде валидаций. Задача контроллера — отреагировать на действие со стороны пользователя.

Код лучше писать максимально единообразно. В случае контроллеров — максимально близко к тому, что выдают генераторы:

```
def create
  @answer = question.answers.new answer_params
  @answer.user = current_user
  if @answer.save
    redirect_to @question, notice: "Answer was saved"
  else
    render 'questions/new', alert: "Unable to save answer"
  end
end
```

Редирект в случае неуспеха не нужен потому, что мы хотим отрендерить страницу вопроса с формой ответа и данными неправильного ответа в ней.

2019-06-29 19:13 UTC, aishek commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit( :body, :user_id)
`user_id` лучше не передавать снаружи, а явно назначать автора прямо в коде контроллера.

2019-06-29 19:13 UTC, aishek commented on app/controllers/answers_controller.rb
> +  def author?
Лучше такой метод написать у пользователя в виде "а являюсь ли я автором для X?"

2019-06-29 19:13 UTC, aishek commented on app/views/questions/show.html.slim
> += form_with model: [ @question, @answer ], local: true do |f|
Для ответа всё ещё нет вывода

2019-06-29 19:13 UTC, aishek commented on config/routes.rb
> +  resources :questions, shallow: true do
Всё ещё не сюда.

2019-06-29 19:13 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect{ post :create, params: { question_id: question, answer: attributes_for(:answer)  } }.to change(question.answers, :count).by(1)
Отлично, а теперь надо ещё убедиться, что создался ответ именно с теми атрибутами, которые мы передали.

2019-06-29 19:13 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
Не увидел этих проверок.

2019-06-29 19:13 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
Надо бы ещё проверить, что вопрос создался именно с теми атрибутами, которые мы передали.

2019-06-29 19:13 UTC, aishek commented on spec/features/answer/delete_spec.rb
> +feature 'Автор может удалить свой ответ, но не может удалить чужой ответ' do
Нужно добавить проверку что у неавторизованного даже нет ссылки на удаление

2019-06-29 22:03 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def create
Вопрос вызывает следующая строка:

  else
    **render 'questions/new', alert: "Unable to save answer"**
  end

т. е. рендерится шаблон для нового вопроса questions#new, а не "мы хотим отрендерить страницу вопроса с формой ответа и данными неправильного ответа в ней". Как отобразить шаблон questions#show из контроллера answers_controller? Т. е. как отобразить описано в документации, но предоставлением данных для шаблона questions#show занимается метод show контроллера questions, который можно вызвать только через редирект. Или я не о том?

2019-06-30 06:20 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit( :body, :user_id)
fixed

2019-06-30 07:01 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def author?
fixed

2019-06-30 16:32 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect{ post :create, params: { question_id: question, answer: attributes_for(:answer)  } }.to change(question.answers, :count).by(1)
fixed

2019-06-30 16:49 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
fixed

2019-06-30 17:49 UTC, DmitryKilin commented on spec/features/answer/delete_spec.rb
> +feature 'Автор может удалить свой ответ, но не может удалить чужой ответ' do
fixed

2019-07-01 08:51 UTC, aishek commented on app/controllers/answers_controller.rb
> +  def create
Да, всё верно. Не надо воспринимать мой код как 100% всегда работающий эталон. Лучше — как иллюстрацию идеи. Надо как-то так:

```
flash[:notice] = 'Unable to save answer'
render 'questions/show'
```

2019-07-01 09:07 UTC, aishek requested changes

2019-07-01 09:07 UTC, aishek commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
Лиший `user_id`.

2019-07-01 09:07 UTC, aishek commented on app/controllers/answers_controller.rb
> +  def create
Это нужно доделать.

2019-07-01 09:07 UTC, aishek commented on app/models/user.rb
> +    some_instance.respond_to?(:user) && some_instance.user_id == self.id
Отлично, но можно ещё чуть лучше: `some_instance&.user_id == self.id`

2019-07-01 09:07 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before {post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)  }}
Не надо проверяемое действие отправлять в `before`, его нужно всегда вызывать в теле самого теста.

2019-07-01 09:07 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).body).to eq (answer.body)
Тут нарушается принцип "чёрного ящика", что сделает более болезненным переименование переменной `answer` в контроллере. И из теста непонятно, какая связь между этой переменной и нашим действием.

Надо как-то так:

```
it 'saves authored answer with passed attributes' do
  new_answer_attributes = attributes_for(:answer)
  expect {
    post :create, params: { question_id: question, answer: new_answer_attributes }
  }.to change(question.answers, :count).by(1)

  new_answer = question.answers.find_by(new_answer_attributes)
  expect { new_answer }.to be_present
  expect { user }.to be_author(new_answer)
end
```

2019-07-01 09:07 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
Не то, посмотри пример выше

2019-07-01 09:07 UTC, aishek commented on spec/features/answer/delete_spec.rb
> +feature 'Автор может удалить свой ответ, но не может удалить чужой ответ' do
Оно, спасибо. Идеально бы ещё два контекста описать — тесты для авторизованного и тесты для неавторизованного.

2019-07-01 09:07 UTC, aishek commented on app/models/user.rb
> +  def author?(some_instance)
Нужен юнит-тест на этот метод.

2019-07-01 11:52 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def create
fixed

2019-07-01 11:52 UTC, DmitryKilin commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
fixed

2019-07-01 12:57 UTC, DmitryKilin commented on app/models/user.rb
> +  def author?(some_instance)
fixed

2019-07-01 12:57 UTC, DmitryKilin commented on app/models/user.rb
> +    some_instance.respond_to?(:user) && some_instance.user_id == self.id
fixed

2019-07-01 13:05 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      before {post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)  }}
fixed

2019-07-01 13:26 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).body).to eq (answer.body)
fixed

2019-07-01 13:35 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
fixed

2019-07-01 14:19 UTC, aishek requested changes

2019-07-01 14:19 UTC, aishek commented on app/views/questions/show.html.slim
> += form_with model: [ @question, @answer ], local: true do |f|
Всё ещё нет вывода ошибок для ответа.

2019-07-01 14:19 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        question = create(:question)
Это лучше в `let`

2019-07-01 14:19 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect(new_answer).to be
Что за запись?

2019-07-01 14:19 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect user.author?(new_answer)
Это тоже странное. Лучше всего использовать https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-07-01 14:19 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer)).to eq answer
Эта проверка не только бесполезная но и вредная

2019-07-01 14:19 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +
Просто `change(Question, :count)`

2019-07-01 14:19 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +      before { post :create, params: { question: attributes_for(:question) } }
Никогда так не делай. Надо явно в тесте вызывать проверяемое действие.

2019-07-01 14:19 UTC, aishek commented on spec/features/question/delete_spec.rb
> +feature 'Автор может удалить свой вопрос, но не может удалить чужой вопрос' do
Проверь отсутствие ссылки для неавторизованного.

2019-07-01 14:19 UTC, aishek commented on app/models/user.rb
> +  def author?(some_instance)
Не вижу тестов для этого метода.

2019-07-01 14:36 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        question = create(:question)
fixed

2019-07-01 15:08 UTC, DmitryKilin commented on spec/features/answer/delete_spec.rb
> +feature 'Автор может удалить свой ответ, но не может удалить чужой ответ' do
done

2019-07-01 15:18 UTC, DmitryKilin commented on spec/features/question/delete_spec.rb
> +feature 'Автор может удалить свой вопрос, но не может удалить чужой вопрос' do
done

2019-07-01 15:51 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect user.author?(new_answer)
done

2019-07-01 15:59 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +
done

2019-07-01 16:02 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +      before { post :create, params: { question: attributes_for(:question) } }
Не буду :( ! В `answer_controller` убрал, здесь нет.

done

2019-07-01 16:06 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect(new_answer).to be
done

2019-07-01 16:06 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer)).to eq answer
Удалить ?

2019-07-01 16:42 UTC, DmitryKilin commented on app/models/user.rb
> +  def author?(some_instance)
done

2019-07-01 16:42 UTC, DmitryKilin commented on app/views/questions/index.html.slim
> +h1= 'Questions list'
done

2019-07-01 16:42 UTC, DmitryKilin commented on app/views/questions/show.html.slim
> += form_with model: [ @question, @answer ], local: true do |f|
done?

2019-07-01 17:15 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
>  RSpec.describe QuestionsController, type: :controller do
done

2019-07-01 17:15 UTC, DmitryKilin commented on spec/features/answer/create_spec.rb
> +    visit question_path(question)
done

2019-07-01 17:16 UTC, DmitryKilin commented on spec/features/sign_up_spec.rb
> +  scenario "Visitor fills correct the register form, clicks the 'Sign up' button and redirects to the confirmation page" do
done

2019-07-01 17:26 UTC, DmitryKilin commented on spec/features/sign_up_spec.rb
> +  scenario "Visitor fills correct the register form, clicks the 'Sign up' button and redirects to the confirmation page" do
done

2019-07-01 19:18 UTC, aishek requested changes

2019-07-01 19:18 UTC, aishek commented on app/views/answers/show.html.slim
> += link_to 'Delete', answer_path(@answer), method: :delete if user_signed_in?
Любой авторизованный может удалить любой ответ?

2019-07-01 19:18 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect(user.author?(new_answer)).to be_truthy
`expect(user).to be_author(new_answer)` см. https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-07-01 19:18 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)}
Давай одинаково, в параметр `question_id` всегда передавай объект.

2019-07-01 19:18 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect user.author?(new_question)
Тут лучше предикат-матчер

2019-07-01 19:18 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    context 'Authenticated user is not the author.' do
А неавторизованный?

2019-07-01 19:18 UTC, aishek commented on spec/features/answer/create_spec.rb
> +  scenario 'User tries to give a impermissible answer' do
Надо проверить неавторизованного пользователя

2019-07-01 19:18 UTC, aishek commented on spec/features/question/delete_spec.rb
> +feature 'Автор может удалить свой вопрос, но не может удалить чужой вопрос' do
Не нашёл ссылки на удаление в этом спеке

2019-07-01 19:18 UTC, aishek commented on spec/models/user_spec.rb
> +  it "creates user and relative answer, then checks user 'author?' method returns true." do
Во втором тесте полезнее проверить поведение для ответа другого пользователя.

И поработай над организацией кода тестов, например:

```
describe '#author?' do
  it 'true if resource user is the same' do
    # ...
  end

  it 'false if resource user is other user' do
    # ...
  end
end
```

2019-07-01 21:28 UTC, DmitryKilin commented on app/views/answers/show.html.slim
> += link_to 'Delete', answer_path(@answer), method: :delete if user_signed_in?
Не сможет, поскольку контроллер `answer_controller#destroy` не пропустит.

Изменил интеграционный тест с тем, чтобы проверял отсутствие ссылки `Delete`. 

Проверку ограничений на пользователя реализовал в функциональных тестах `answer_controller_spec`

Добавил ограничение во вьюху `show.html.slim`

done

2019-07-01 21:33 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect(user.author?(new_answer)).to be_truthy
done

2019-07-01 21:35 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)}
done

2019-07-01 21:36 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer)).to eq answer
done

2019-07-01 21:42 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +    context 'Authenticated user is not the author.' do
done

2019-07-01 21:59 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        expect user.author?(new_question)
done

2019-07-01 22:13 UTC, DmitryKilin commented on spec/features/answer/create_spec.rb
> +  scenario 'User tries to give a impermissible answer' do
Есть сценарий, проверяющий, что только аутентифицированный пользователь может создавать ответы.

done

2019-07-02 10:55 UTC, DmitryKilin commented on spec/features/question/delete_spec.rb
> +feature 'Автор может удалить свой вопрос, но не может удалить чужой вопрос' do
done

2019-07-02 11:23 UTC, DmitryKilin commented on spec/models/user_spec.rb
> +  it "creates user and relative answer, then checks user 'author?' method returns true." do
done

2019-07-02 14:57 UTC, aishek requested changes

2019-07-02 14:57 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect{post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)  }}.to change(answer.question.answers, :count).by(1)
Странные `answer.question_id` и `answer.question.answers`. Почему не воспользоваться вопросом из строки 11?

2019-07-02 14:57 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Я бы ещё в этот тест и тесты выше добавил бы проверку для неавторизованного.

2019-07-02 14:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +      it 'deletes the question' do
Идеально бы добавить проверку, что удалён именно переданный вопрос.

2019-07-02 14:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        new_question_attributes = attributes_for(:question)
Это присваивание нужно сделать до выполнения действия, и эту переменную использовать в действии. Ведь если у тебя в фабрике используется последовательность, то два вызова `attributes_for(:question)` дадут разные хэши.

2019-07-02 14:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    context 'without valid attributes' do
И неавторизованного бы проверить.

2019-07-02 14:57 UTC, aishek commented on spec/features/answer/delete_spec.rb
> +      visit answer_path(answer)
Это нужно в тест

2019-07-02 14:57 UTC, aishek commented on spec/features/sign_out_spec.rb
> +    click_on 'Sign out'
Для кнопок лучше https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FActions:click_button — дескриптивнее получается

2019-07-02 15:01 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect{post :create, params: { question_id: answer.question_id, answer: attributes_for(:answer)  }}.to change(answer.question.answers, :count).by(1)
done

2019-07-02 16:04 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
done

2019-07-02 16:18 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +      it 'deletes the question' do
done

2019-07-02 16:23 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        new_question_attributes = attributes_for(:question)
done

2019-07-02 16:24 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +    context 'without valid attributes' do
done

2019-07-02 16:27 UTC, DmitryKilin commented on spec/features/answer/delete_spec.rb
> +      visit answer_path(answer)
done

2019-07-03 10:17 UTC, aishek requested changes

2019-07-03 10:17 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { sign_out(user) }
Лучше логинить внутри контекстов нужных пользователей -- так меньше телодвижений и быстрее прогон всех тестов.

2019-07-03 10:17 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      it 'sugested to authenticate.' do
И обязательно проверить что не создался ответ

2019-07-03 10:17 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: answer.question, answer: attributes_for(:answer)}
Тут естественнее просто вопрос передать, а не вопрос от какого-то ответа

2019-07-03 10:17 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(Answer, :count).by(-1)
Тут лучше "поуже" проверить -- что удалился у конкретного вопроса один ответ. Ну и проверить что именно переданный ответ удалён.

2019-07-03 10:17 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        question.reload
Перезапросил из базы один вопрос, а проверяешь другой

2019-07-03 10:17 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect(Question.find_by(id: question.id)).to be_nil
можно ещё `Question.exists?(question.id)`

2019-07-03 10:17 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { question: attributes_for(:question) }
Проверить что не создалось нужно

2019-07-04 07:13 UTC, DmitryKilin commented on spec/features/sign_out_spec.rb
> +    click_on 'Sign out'
В моём случае - `click_link`. Но могу лишь догадываться  какой элемент меню (ссылка или кнопка) будет вызываться, оставил `click_on`.

2019-07-04 07:13 UTC, DmitryKilin commented on spec/features/sign_out_spec.rb
> +    click_on 'Sign out'
done

2019-07-04 07:18 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      before { sign_out(user) }
done

2019-07-04 07:40 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      it 'sugested to authenticate.' do
done

2019-07-04 07:44 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: answer.question, answer: attributes_for(:answer)}
done

2019-07-04 07:51 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(Answer, :count).by(-1)
done

2019-07-04 07:55 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        question.reload
done

2019-07-04 08:00 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        expect(Question.find_by(id: question.id)).to be_nil
done

2019-07-04 08:13 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { question: attributes_for(:question) }
done

2019-07-04 09:40 UTC, aishek requested changes

2019-07-04 09:40 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { sign_out(user) }
А зачем логаут остался?

2019-07-04 09:40 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      it 'sugested to authenticate.' do
Тут можно было проще -- проверить что количество не изменилось

2019-07-04 09:40 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { post :create, params: { question_id: answer.question, answer: attributes_for(:answer, :invalid) } }
Тут и везде ниже никогда не пиши тестируемое действие в `before`

2019-07-04 09:40 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        old_question = question
Зачем это присваивание?

2019-07-04 09:40 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect(question.title).to eq old_question.title
Тест ничего не проверяет, так как ты не перезапрашиваешь состояние из базы

2019-07-04 11:27 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        expect(question.title).to eq old_question.title
done

2019-07-04 11:27 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        old_question = question
done

2019-07-04 11:27 UTC, DmitryKilin commented on spec/controllers/answers_controller_spec.rb
> +      before { post :create, params: { question_id: answer.question, answer: attributes_for(:answer, :invalid) } }
done

2019-07-04 14:59 UTC, aishek requested changes

2019-07-04 14:59 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect(question.title).to eq old_question.title
Я бы просто с константами сравнил, ну да ладно

2019-07-04 14:59 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      it 'sugested to authenticate.' do
Смотри, хоть и понятно, что всех возможных ошибок не поймаешь, но когда в базу ничего не должно попасть, то выгоднее сделать проверку максимально широкой (`Answer.count`), а когдо должно -- максимально узкой.

2019-07-04 14:59 UTC, aishek commented on spec/features/answer/delete_spec.rb
> +      expect(page).to have_content "Answer have been deleted!"
Идеально бы во всех сценариях удаления ответить на вопрос "а что стало с текстом вопроса?" (и ответа соответственно).

2019-07-04 18:49 UTC, merged