Lesson 6
DmitryKilin/qna pull request #4
Opened 2019-07-23 21:51 UTC by DmitryKilin

2019-07-24 07:55 UTC, vkurennov requested changes

2019-07-24 07:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def star
слишком много бизнес-логики в контроллере, контроллер не должен выполнять какие-то действия с моделями, это делают сами модели. Контрллер лишь отвечает за вызов нужного метода у модели, а также за права доступа и рендер/редирект. Т.е. нужно сделать метод модели, который будет делать все, что нужно, а здесь просто его вызывать

2019-07-24 07:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    render :star
это лишнее, т.к. по-умолчанию, экшн рендерит одноименный вид.

2019-07-24 07:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.ranked = true
используй метод update, чтобы одновременно присвоить значения атрибутам и сохранить модель

2019-07-24 07:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def unstar
здесь те же замечания: это должен быть метод модели.

2019-07-24 07:55 UTC, vkurennov commented on app/models/answer.rb
> +class RankedExclusivity < ActiveModel::Validator
1. Валидаторы выносят в отдельные файлы, т.к. каждый класс должен быть в своем файле.
2. Тут вообще лучше сделать кастомную валидацию прямо в модели, т.к. класс валидатора имеет смысл, если такая валидация будет использоваться в разных моделях. Но тут проверка очень спеецифичная, нет смысла выносить ее в класс

2019-07-24 07:55 UTC, vkurennov commented on app/views/answers/update.js.erb
> +$('.answers').html('<%= j render @question.answers.order(ranked: :desc) %>');
тут надо обновлять только измененный ответ, а не весь список

2019-07-24 17:10 UTC, DmitryKilin commented on app/models/answer.rb
> +class RankedExclusivity < ActiveModel::Validator
fixed

2019-07-24 17:11 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +    render :star
fixed

2019-07-24 19:59 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def star
fixed

2019-07-24 20:02 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +  def unstar
fixed

2019-07-24 20:03 UTC, DmitryKilin commented on app/views/answers/update.js.erb
> +$('.answers').html('<%= j render @question.answers.order(ranked: :desc) %>');
fixed

2019-07-24 20:08 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +    @answer.ranked = true
?

2019-07-25 07:53 UTC, vkurennov requested changes

2019-07-25 07:53 UTC, vkurennov commented on app/models/answer.rb
> +  def rank
1. Как я уже писал - вместо назначения атрибута + save стоит сделать update
2. т.к. тут 2 апдейта, надо их объеденить в транзакцию, чтобы изменения были атомарными. Только учти, что в транзакциях надо использовать bang-весрии методов, т.к. она откатывается только в случае исключений

2019-07-25 07:53 UTC, vkurennov commented on app/models/answer.rb
> +  def unrank
используй здесь update

2019-07-25 07:53 UTC, vkurennov commented on app/models/answer.rb
> +      prev_ranked.ranked = false
это ровно то, что делает твой метод unrank, используй его

2019-07-25 07:53 UTC, vkurennov commented on app/models/answer.rb
> +  def ranked_exclusivity
методы-валидаторы не предназначены для вызова вне класса, поэтому их нужно объявлять в private-секции

2019-07-25 11:21 UTC, DmitryKilin commented on app/models/answer.rb
> +  def rank
fixed

2019-07-25 11:22 UTC, DmitryKilin commented on app/models/answer.rb
> +  def unrank
fixed

2019-07-25 11:24 UTC, DmitryKilin commented on app/models/answer.rb
> +      prev_ranked.ranked = false
fixed

Подумал оставить `unrank` ради его не бэнговой версии `update`.

2019-07-25 11:24 UTC, DmitryKilin commented on app/models/answer.rb
> +  def ranked_exclusivity
fixed

2019-07-25 13:20 UTC, vkurennov approved these changes

2019-07-25 13:20 UTC, vkurennov commented on app/models/answer.rb
> +    Answer.transaction do
можно просто transaction, без Answer, у моделей есть такой приватный метод

2019-07-25 13:20 UTC, vkurennov commented on app/models/answer.rb
> +      self.update!(ranked: true)
self здесь не обязателен

2019-07-28 18:35 UTC, aishek requested changes

2019-07-28 18:35 UTC, aishek commented on app/views/questions/_form.html.slim
> +-if @question.files.attached?
Похоже тут просится партиал

2019-07-28 18:35 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: {question_id: question, answer: new_answer_attributes  }
Файлики бы тут проверить тоже

2019-07-28 18:35 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: {question: new_question_attributes }
И тут бы файлики проверить

2019-07-28 18:35 UTC, aishek commented on spec/models/user_spec.rb
> +
Тут нужно проверить новый метод проверки авторства аттачмента.

2019-07-28 19:37 UTC, DmitryKilin commented on app/views/questions/_form.html.slim
> +-if @question.files.attached?
fixed

2019-07-28 21:12 UTC, DmitryKilin commented on spec/models/user_spec.rb
> +
fixed

2019-07-28 22:00 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: {question: new_question_attributes }
fixed

2019-07-29 07:27 UTC, aishek requested changes

2019-07-29 07:27 UTC, aishek commented on spec/models/user_spec.rb
> +    it { is_expected.to respond_to(:attachment_owner?) }
Избыточный тест

2019-07-29 07:27 UTC, aishek commented on app/views/questions/_form.html.slim
> +-if @question.files.attached?
Я имел ввиду общий и для вопроса и для ответа

2019-07-29 19:31 UTC, merged