Lesson-8
DmitryKilin/qna pull request #5
Opened 2019-08-04 19:11 UTC by DmitryKilin

2019-08-05 07:44 UTC, aishek requested changes

2019-08-05 07:44 UTC, aishek commented on app/views/questions/show.html.slim
> +    #links
Просится в партиал

2019-08-05 07:44 UTC, aishek commented on spec/models/link_spec.rb
> +  describe  '#gist?' do
Ещё нужен тест на `gist_id`. Публичные методы (кроме простых геттеров, сеттеров и делегатов) как правило надо тестировать.

2019-08-05 07:44 UTC, aishek commented on spec/features/question/delete_link_spec.rb
> +  background {question.links.create(name: "Google", url: "https://google.ru")}
А почему не создать ссылку по аналогии с вопросом?

2019-08-05 07:44 UTC, aishek commented on spec/features/answer/delete_link_spec.rb
> +  background {answer.links.create(name: "Google", url: "https://google.ru")}
Почему не создать ссылку по аналогии с ответом?

2019-08-05 07:44 UTC, aishek commented on spec/features/answer/delete_link_spec.rb
> +  given(:user) { create(:user, email: 'user@test.com', password: '12345678') }
Зачем задавать адрес электронной почты и пароль?

2019-08-05 07:44 UTC, aishek commented on spec/controllers/links_controller_spec.rb
> +  before{question.links.create(name: "Gist", url: my_gist)}
Почему ссылку не создать по аналогии с вопросом?

2019-08-05 07:44 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        new_question.reward.attach(create_file_blob)
Так, а это что? Насколько я понимаю, это должно делаться внутри контроллера.

2019-08-05 07:44 UTC, aishek commented on spec/features/answer/create_spec.rb
> +      page.all('input.form-control',{id: %r{answer_links_attributes_.}})[0].set('Favorite searching1')
Почему не использовать https://github.com/teamcapybara/capybara#interacting-with-forms?

2019-08-05 09:34 UTC, DmitryKilin commented on app/views/questions/show.html.slim
> +    #links
fixed

2019-08-05 12:10 UTC, DmitryKilin commented on spec/models/link_spec.rb
> +  describe  '#gist?' do
fixed

2019-08-05 13:40 UTC, DmitryKilin commented on spec/features/question/delete_link_spec.rb
> +  background {question.links.create(name: "Google", url: "https://google.ru")}
?

2019-08-05 13:45 UTC, DmitryKilin commented on spec/features/answer/delete_link_spec.rb
> +  background {answer.links.create(name: "Google", url: "https://google.ru")}
?

2019-08-05 13:47 UTC, DmitryKilin commented on spec/features/answer/delete_link_spec.rb
> +  given(:user) { create(:user, email: 'user@test.com', password: '12345678') }
fixed

2019-08-05 14:09 UTC, DmitryKilin commented on spec/controllers/links_controller_spec.rb
> +  before{question.links.create(name: "Gist", url: my_gist)}
fixed

2019-08-05 15:55 UTC, DmitryKilin commented on spec/controllers/questions_controller_spec.rb
> +        new_question.reward.attach(create_file_blob)
fixed

2019-08-06 18:13 UTC, DmitryKilin commented on spec/features/answer/create_spec.rb
> +      page.all('input.form-control',{id: %r{answer_links_attributes_.}})[0].set('Favorite searching1')
fixed

2019-08-06 20:43 UTC, aishek requested changes

2019-08-06 20:43 UTC, aishek commented on spec/models/link_spec.rb
> +      question.links.create(attributes_for(:link, :gist))
Почему это строка тут? Это же подготовка данных

2019-08-06 20:43 UTC, aishek commented on app/models/user.rb
> +  def rewarded_answers
Коряво. Почему просто не сделать ассоциацию наград?

2019-08-07 04:03 UTC, DmitryKilin commented on spec/models/link_spec.rb
> +      question.links.create(attributes_for(:link, :gist))
fixed

2019-08-07 08:55 UTC, DmitryKilin commented on app/models/user.rb
> +  def rewarded_answers
cosi-cosi

2019-08-07 10:50 UTC, aishek requested changes

2019-08-07 10:50 UTC, aishek commented on spec/features/user/view_rewards_spec.rb
> +  given!(:answer){create(:answer, :ranked_true, user: user)}
Надо стремиться к тому, чтобы вместо `:ranked_true` писать просто `ranked: true`. Для этого нужно в фабрике для `body` задать содержимое с последовательностью например, а в тестах ссылаться не на конкретную строку в body, а на сущность собранную фабрикой как лучшую.

2019-08-07 10:50 UTC, aishek commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
Нужны тесты для `rank` и `unrank`.

2019-08-07 14:03 UTC, DmitryKilin commented on spec/features/user/view_rewards_spec.rb
> +  given!(:answer){create(:answer, :ranked_true, user: user)}
fixed

2019-08-07 20:38 UTC, aishek approved these changes

2019-08-07 20:38 UTC, aishek commented on spec/models/answer_spec.rb
> +      expect(answer_first.ranked).to be_falsey
Не забывай про https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-08-08 08:52 UTC, vkurennov approved these changes

2019-08-08 08:52 UTC, vkurennov commented on app/models/answer.rb
> +      question.prize&.update(user: nil)
раз у тебя транзакция, то надо использовать bang-версии методов, т.к. транзакция откатывается только в случае исключений

2019-08-08 09:32 UTC, merged