Lesson 10
DmitryKilin/qna pull request #6
Opened 2019-08-14 12:42 UTC by DmitryKilin

2019-08-14 20:52 UTC, aishek requested changes

2019-08-14 20:52 UTC, aishek commented on app/assets/javascripts/vote.js
> +console.log( elID );
Отладочый код надо убирать

2019-08-14 20:52 UTC, aishek commented on app/controllers/concerns/voted.rb
> +  def obj_votable
Метод бесполезен. Лучше внеси в `make_vote`

2019-08-14 20:52 UTC, aishek commented on app/controllers/concerns/voted.rb
> +  def model_klass
Метод бесполезен

2019-08-14 20:52 UTC, aishek commented on app/models/concerns/votable.rb
> +      votes.create(user: voter, definition: DEFINITIONS[option])
Если ты тут ожидаешь, что новый объект в `votes` точно появится, то используй `create!` чтобы явно отследить обратное

2019-08-14 20:52 UTC, aishek commented on app/models/vote.rb
> +  belongs_to :votable, polymorphic: true
Можно на уровне валидации задать требование голосовать только один раз за одну сущность

2019-08-14 20:52 UTC, aishek commented on spec/features/vote/vote_spec.rb
> +    expect( page ).to have_selector( '.poll' )
А что проверяет этот тест?

2019-08-14 20:52 UTC, aishek commented on spec/models/answer_spec.rb
> +  it_behaves_like 'votable'
Два раза добавлен?

2019-08-14 20:52 UTC, aishek commented on spec/support/shared/voted_controller.rb
> +RSpec.shared_examples 'voted' do
Что с неавторизованным?

2019-08-15 08:52 UTC, DmitryKilin commented on app/assets/javascripts/vote.js
> +console.log( elID );
fixed

2019-08-15 08:54 UTC, DmitryKilin commented on app/controllers/concerns/voted.rb
> +  def obj_votable
fixed

2019-08-15 08:54 UTC, DmitryKilin commented on app/controllers/concerns/voted.rb
> +  def model_klass
fixed

2019-08-15 08:55 UTC, DmitryKilin commented on app/models/concerns/votable.rb
> +      votes.create(user: voter, definition: DEFINITIONS[option])
fixed

2019-08-15 09:33 UTC, DmitryKilin commented on app/models/vote.rb
> +  belongs_to :votable, polymorphic: true
fixed

2019-08-15 09:34 UTC, DmitryKilin commented on spec/features/vote/vote_spec.rb
> +    expect( page ).to have_selector( '.poll' )
fixed

2019-08-15 09:35 UTC, DmitryKilin commented on spec/models/answer_spec.rb
> +  it_behaves_like 'votable'
fixed

2019-08-15 10:22 UTC, DmitryKilin commented on spec/support/shared/voted_controller.rb
> +RSpec.shared_examples 'voted' do
fixed

2019-08-15 11:01 UTC, aishek approved these changes

2019-08-15 11:01 UTC, aishek commented on app/models/concerns/votable.rb
> +  def find_prev_vote(voter)
Тоже лишний метод

2019-08-15 11:01 UTC, aishek commented on app/models/vote.rb
> +  belongs_to :votable, polymorphic: true
Индекс — это хорошо. Почему валидацию не добавить на уникальность?

2019-08-15 11:25 UTC, vkurennov approved these changes

2019-08-15 13:14 UTC, DmitryKilin commented on app/models/concerns/votable.rb
> +  def find_prev_vote(voter)
fixed

2019-08-15 14:45 UTC, merged