Lesson 11
DmitryKilin/qna pull request #7
Opened 2019-09-17 20:57 UTC by DmitryKilin

2019-09-18 08:37 UTC, aishek requested changes
Нужно дополнить тесты моделей и контроллеров. Также перепроверить, появляются ли комменты и ответы на страницах других сущностей.

2019-09-18 08:37 UTC, aishek commented on app/controllers/answers_controller.rb
> +    files = []
Подобные конструкции в Руби лучше писать через `map`:

```
files = @answer.files.map do |file|
  { id: file.id, url: url_for(file), name: file.filename.to_s }
end
```

2019-09-18 08:37 UTC, aishek commented on app/views/comments/_comment.html.slim
> +  p class="small"
Такое можно проще: `p.small`

2019-09-18 08:37 UTC, aishek commented on app/views/comments/_form.html.slim
> +- if resource.comments.exists?
Без этого условного оператора сработает точно также

2019-09-18 08:37 UTC, aishek commented on app/views/questions/show.html.slim
> +.question *{ 'data-question-id': @question.id }
Странная запись. Почему не `.question data-question-id=@question.id`?

2019-09-18 08:37 UTC, aishek commented on app/controllers/concerns/commented.rb
> +module Commented
Почему не завести отдельный контроллер с методом `create`?

2019-09-18 08:37 UTC, aishek commented on spec/features/answer/create_spec.rb
> +        visit question_path(question)
Полезно проверить что на странице другого вопроса ответа не появится

2019-09-18 08:37 UTC, aishek commented on spec/features/comment/comment_spec.rb
> +        expect(page).to have_content 'My comment'
Полезно одновременно проверить страницу другого вопроса

2019-09-18 16:22 UTC, DmitryKilin commented on app/controllers/answers_controller.rb
> +    files = []
fixed

2019-09-18 16:40 UTC, DmitryKilin commented on app/views/comments/_comment.html.slim
> +  p class="small"
fixed

2019-09-18 16:41 UTC, DmitryKilin commented on app/views/comments/_form.html.slim
> +- if resource.comments.exists?
fixed

2019-09-18 16:43 UTC, DmitryKilin commented on app/views/questions/show.html.slim
> +.question *{ 'data-question-id': @question.id }
fixed

2019-09-18 16:43 UTC, DmitryKilin commented on app/controllers/concerns/commented.rb
> +module Commented
fixed

2019-09-18 17:19 UTC, DmitryKilin commented on spec/features/comment/comment_spec.rb
> +        expect(page).to have_content 'My comment'
fixed

2019-09-18 17:19 UTC, DmitryKilin commented on spec/features/answer/create_spec.rb
> +        visit question_path(question)
fixed

2019-09-19 08:21 UTC, aishek requested changes

2019-09-19 08:21 UTC, aishek commented on app/assets/javascripts/comments.js
> +                    '<div class="alert alert-danger alert-dismissible fade show"' +
Хранить разметку в JS — не очень идея. Лучше использовать какой-нибудь клиентский шаблонизатор, например skim

2019-09-19 08:21 UTC, aishek commented on config/routes.rb
> +    resource :comments, only: %i[create]
Почему не завести один контроллер комментариев?

2019-09-19 08:21 UTC, aishek commented on spec/controllers/comments_controller_spec.rb
> +  describe 'POST #create' do
Надо ещё рендеринг проверить

2019-09-19 12:45 UTC, DmitryKilin commented on app/assets/javascripts/comments.js
> +                    '<div class="alert alert-danger alert-dismissible fade show"' +
fixed

2019-09-19 12:56 UTC, DmitryKilin commented on config/routes.rb
> +    resource :comments, only: %i[create]
fixed

2019-09-19 16:40 UTC, aishek approved these changes

2019-09-19 16:40 UTC, aishek commented on app/assets/javascripts/comments.js
> +        // '<div class="comment" id="comment-' + data['id'] + '">' +
Закомментированный код надо удалять

2019-09-19 16:40 UTC, aishek commented on app/assets/javascripts/templates/comment.jst.skim
> +.comment id="comment-#{@data.id}"
Надо `@data` --> `@comment`

2019-09-19 19:07 UTC, merged