Lesson 12
DmitryKilin/qna pull request #8
Opened 2019-10-02 11:03 UTC by DmitryKilin

2019-10-02 14:54 UTC, aishek requested changes
В целом всё работает, но хочется больше внимания к деталям.

И рекомендую сделать-таки усложнённое задание.

2019-10-02 14:54 UTC, aishek commented on config/application.rb
> +    config.autoload_paths += [config.root.join('app')]
А без этого точно не работает?

2019-10-02 14:54 UTC, aishek commented on app/models/user.rb
> +    self.authorizations.create(provider: auth.provider, uid: auth.uid)
Тут ожидается что авторизация точно сохраниться, поэтому нужно использовать `self.authorizations.create!` и метод назвать `create_authorization!`

2019-10-02 14:54 UTC, aishek commented on app/services/find_for_oauth.rb
> +    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
Можно проще: `authorization = Authorization.find_by(provider: auth.provider, uid: auth.uid.to_s)`

2019-10-02 14:54 UTC, aishek commented on app/services/find_for_oauth.rb
> +    user = User.where(email: email).first
user = User.find_by(email: email)

2019-10-02 14:54 UTC, aishek commented on app/controllers/oauth_callbacks_controller.rb
> +      redirect_to root_path, alert: 'Fail to authorize user!'
В каком случае мы попадаем в эту ветку?

2019-10-02 19:37 UTC, DmitryKilin commented on config/application.rb
> +    config.autoload_paths += [config.root.join('app')]
В Rails 5.2.3 не работает.

fixed

2019-10-02 19:45 UTC, DmitryKilin commented on app/models/user.rb
> +    self.authorizations.create(provider: auth.provider, uid: auth.uid)
fixed

2019-10-02 19:47 UTC, DmitryKilin commented on app/services/find_for_oauth.rb
> +    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
fixed

2019-10-02 19:47 UTC, DmitryKilin commented on app/services/find_for_oauth.rb
> +    user = User.where(email: email).first
fixed

2019-10-02 20:05 UTC, DmitryKilin commented on app/controllers/oauth_callbacks_controller.rb
> +      redirect_to root_path, alert: 'Fail to authorize user!'
Если только сознательно вернуть методом find_for_oauth значение nil.  Полезного применения этого я не смог придумать!

fixed

2019-10-02 20:23 UTC, DmitryKilin commented on app/controllers/oauth_callbacks_controller.rb
> +      redirect_to root_path, alert: 'Fail to authorize user!'
Но протестить этот случай, о чём упоминается в скринкасте, было бы не плохо. Если контроллер не вернёт redirect или вьюху, то соответствующие тесты не проходят.

2019-11-25 14:33 UTC, vkurennov requested changes
Не хватает фича-тестов на этот функционал

2019-11-25 14:33 UTC, vkurennov commented on app/controllers/oauth_callbacks_controller.rb
> +  def demand_email
вот эти вещи, конечно, стоит в другом контроллере сделать

2019-11-25 14:33 UTC, vkurennov commented on app/services/find_for_oauth.rb
> +      password = Devise.friendly_token[0, 6]
коротковат пароль, даже временный. хотя бы 10 символов нужно

2019-11-25 14:33 UTC, vkurennov commented on spec/controllers/oauth_callbacks_controller_spec.rb
> +      expect(response).to redirect_to demand_email_path
а где запрос-то? может, поэтому и 200, что там  информация о последнем ответе, либо вообще только что приоинициализированный ответ, он по-умолчанию со статусом 200 создан

2019-11-29 17:11 UTC, vkurennov approved these changes

2019-12-02 15:30 UTC, merged